package app;

public enum Column {
	FEED_PRODUCT_TYPE, ITEM_SKU, BRAND_NAME, ITEM_NAME, MANUFACTURER, ITEM_TYPE, 
	STANDARD_PRICE, QUANTITY, MAIN_IMAGE_URL, SWATCH_IMAGE_URL, OTHER_IMAGE_URL1, 
	OTHER_IMAGE_URL2, OTHER_IMAGE_URL3, OTHER_IMAGE_URL4, OTHER_IMAGE_URL5, 
	OTHER_IMAGE_URL6, OTHER_IMAGE_URL7, OTHER_IMAGE_URL8, PARENT_CHILD, PARENT_SKU, 
	RELATIONSHIP_TYPE, VARIATION_THEME, PRODUCT_DESCRIPTION, MODEL, BULLET_POINT1, 
	BULLET_POINT2, BULLET_POINT3, BULLET_POINT4, BULLET_POINT5, TARGET_AUDIENCE_BASE, 
	SPECIFIC_USES_KEYWORDS1, SPECIFIC_USES_KEYWORDS2, SPECIFIC_USES_KEYWORDS3, 
	TARGET_AUDIENCE_KEYWORDS1, TARGET_AUDIENCE_KEYWORDS2, TARGET_AUDIENCE_KEYWORDS3, 
	THESAURUS_ATTRIBUTE_KEYWORDS1, THESAURUS_ATTRIBUTE_KEYWORDS2, THESAURUS_ATTRIBUTE_KEYWORDS3, 
	THESAURUS_ATTRIBUTE_KEYWORDS4, THESAURUS_SUBJECT_KEYWORDS1, THESAURUS_SUBJECT_KEYWORDS2, 
	THESAURUS_SUBJECT_KEYWORDS3, GENERIC_KEYWORDS, OCCASION, COLOR_NAME, COLOR_MAP, 
	SIZE_NAME, SIZE_MAP, MATERIAL_TYPE, STYLE_NAME, WEBSITE_SHIPPING_WEIGHT, 
	WEBSITE_SHIPPING_WEIGHT_UNIT_OF_MEASURE, ITEM_SHAPE, ITEM_HEIGHT, ITEM_LENGTH, ITEM_WIDTH, 
	ITEM_DIMENSIONS_UNIT_OF_MEASURE, ITEM_WEIGHT, ITEM_WEIGHT_UNIT_OF_MEASURE, 
	MERCHANT_SHIPPING_GROUP_NAME, CONDITION_TYPE, FULFILLMENT_LATENCY, CONDITION_NOTE, 
	PRODUCT_TAX_CODE, SALE_PRICE, SALE_FROM_DATE, SALE_END_DATE, ITEM_PACKAGE_QUANTITY, 
	MAX_AGGREGATE_SHIP_QUANTITY, OFFERING_CAN_BE_GIFT_MESSAGED, OFFERING_CAN_BE_GIFTWRAPPED, 
	MAX_ORDER_QUANTITY, NUMBER_OF_SETS, NUMBER_OF_PIECES, INCLUDED_COMPONENTS, MOUNTING_TYPE, 
	MATERIAL_COMPOSITION, ORIENTATION;
	
	@Override
	public String toString() {
		return name().toLowerCase();
	}
}
