package app;

public enum Material {
	ALUMINUM, BAMBOO, BAMBOO_DERIVED_RAYON, BEECH, BIRCH, BRASS, BRONZE, 
	CASHMERE, CAST_IRON, CEDAR, CHENILLE, CHERRY, CHROME, COPPER, COTTON, DENIM, DOWN_AND_FEATHER_FILL, 
	ELM, FABRIC, FLANNEL, FLEECE, GLASS, HARDWOOD, JERSEY, LEATHER, LEATHER_AND_SUEDE, MAHOGANY, 
	MAPLE, MARBLE, MEMORY_FOAM, METAL, MICROFIBER, NICKEL, OAK, PERCALE, PEWTER, PINE, PLASTIC, 
	POLYESTER_AND_POLYESTER_BLEND, POLYURETHANE, RATTAN, RATTAN_AND_WICKER, RECYCLED_MATERIAL, ROSEWOOD, 
	SATEEN, SATIN, SILK, SILVER, STAINLESS_STEEL, STEEL, STONE, SUEDE, SYNTHETIC, TEAK, 
	TERRYCLOTH, TIN, VELVET, VINYL, WALNUT, WICKER, WILLOW, WOOD, WOOL_AND_WOOL_BLEND, 
	WROUGHT_AND_CAST_IRON, POLYRESIN, POLYCAST, WAX, PARAFFIN, OTHER, FIBERGLASS, PAPER, 
	ACRYLIC_COATED_COTTON, CERAMIC
}
