package app;

public enum Style {
	ANTIQUE, ART_DECO, ASIAN, BAROQUE, CAPE_COD, CASUAL, CHINESE, 
	COLONIAL, CONTEMPORARY, COTTAGE, COUNTRY_RUSTIC, ECLECTIC, ENGLISH, FRENCH, FRENCH_COUNTRY, 
	GARDEN, ITALIANATE, JAPANESE, LATIN, LODGE, MEDITERRANEAN, MISSION, MODERN, MOROCCAN, OLD_WORLD, 
	SCANDINAVIAN, SHABBY_CHIC, SHAKER, SOUTHWESTERN, TRADITIONAL, TROPICAL, VICTORIAN
}
